#include "AppSettings.h"
#include "BuildInfo.h"
#include "Localization.h"
#include "NavigationModel.h"
#include "NoteController.h"
#include "NoteModel.h"
#include "NoteStorage.h"
#include "SummaryService.h"

#include <QCoreApplication>
#include <QDate>
#include <QDir>
#include <QGuiApplication>
#include <QIcon>
#include <QQmlApplicationEngine>
#include <QQmlContext>

int main(int argc, char *argv[])
{
    // app owns the Qt event loop and desktop/mobile GUI integration.
    QGuiApplication app(argc, argv);
    app.setApplicationName(QStringLiteral("ABCNote"));
    app.setOrganizationName(QStringLiteral("ABCNote"));
    app.setApplicationVersion(QString::fromLatin1(BuildInfo::version()));
    app.setWindowIcon(QIcon(QStringLiteral(":/icons/icon/ABCNote.ico")));

    const QString applicationDirPath = QCoreApplication::applicationDirPath();
    const QString settingsFilePath = QDir(applicationDirPath).filePath(QStringLiteral("ABCNote.ini"));

    // localization owns persisted UI language selection and translated runtime strings.
    Localization localization(settingsFilePath);

    // appSettings owns persisted user preferences such as the note data directory.
    AppSettings appSettings(settingsFilePath, applicationDirPath, &localization);

    // storage handles JSON note file persistence.
    NoteStorage storage(appSettings.dataRoot());

    // summaryService sends user-authorized AI summary requests.
    SummaryService summaryService(&localization);

    // noteModel exposes the right-side continuous date stream to QML.
    NoteModel noteModel(&storage, &summaryService, &localization);

    // navigationModel exposes the left-side year/month/day rows to QML.
    NavigationModel navigationModel(&storage, &localization);

    // noteController coordinates startup, editing, autosave, and navigation actions.
    NoteController noteController(&storage, &summaryService, &noteModel, &navigationModel, &appSettings, &localization);
    appSettings.setStorage(&storage);
    appSettings.setController(&noteController);

    // aboutToQuit is the final normal-exit chance to flush dirty notes.
    QObject::connect(&app, &QCoreApplication::aboutToQuit, &noteController, &NoteController::flush);

    // engine loads the QML module generated by qt_add_qml_module.
    QQmlApplicationEngine engine;

    // Expose the note stream model to Main.qml and NoteItemDelegate.qml.
    engine.rootContext()->setContextProperty(QStringLiteral("noteModel"), &noteModel);

    // Expose the date navigation model to Main.qml.
    engine.rootContext()->setContextProperty(QStringLiteral("navModel"), &navigationModel);

    // Expose the controller methods and status property to QML.
    engine.rootContext()->setContextProperty(QStringLiteral("noteController"), &noteController);

    // Expose settings methods and data directory properties to QML.
    engine.rootContext()->setContextProperty(QStringLiteral("appSettings"), &appSettings);

    // Expose translation lookup and language metadata to QML.
    engine.rootContext()->setContextProperty(QStringLiteral("i18n"), &localization);

    // Exit with an error when QML fails to load the application window.
    QObject::connect(&engine,
                     &QQmlApplicationEngine::objectCreationFailed,
                     &app,
                     [] { QCoreApplication::exit(-1); },
                     Qt::QueuedConnection);

    // Load Main.qml from the ABCNote QML module.
    engine.loadFromModule(QStringLiteral("ABCNote"), QStringLiteral("Main"));

    // Create/open today's note after QML is ready to receive scroll signals.
    noteController.start(QDate::currentDate());

    // Enter the Qt event loop.
    return app.exec();
}
